---
site_name: ENP.One Docs
theme:
    name: material
    palette:
        primary: black
        accent: amber
    favicon: images/favicon.ico
    logo: https://cdn.enp.one/img/logos/e-w-sm.png
plugins:
    - git-revision-date
    - search
markdown_extensions:
    - admonition
    - codehilite
repo_name: omni/omni-docs
repo_url: https://vcs.enp.one/omni/omni-docs/
nav:
    - Home: index.md
    - Roadmap(s):
        - Redundancy: roadmap/redundancy.md
        - Ansible Automation: roadmap/awx.md
        - CI/CD: roadmap/buildbot.md
        - Autochat: roadmap/irc.md
    - Network:
        - Architecture: network/arc.md
        - Configuration: network/config.md
        - DHCP/DNS: network/dhcp-dns.md
        - Security: network/security.md
        - Web Hosting: network/web.md
    - Virtualization:
        - Virtual Machines: virtualization/vms.md
        - Docker: virtualization/docker.md
    - Applications:
        - Gitea: applications/gitea.md
        - Plex: applications/plex.md
        - Nextcloud: applications/nextcloud.md
        - Bitwarden: applications/bitwarden.md
    - Hardware:
        - Dell PowerEdge R410: hardware/poweredge-r410.md
        - EdgeRouter Lite: hardware/erl.md
        - Workstations: hardware/workstations.md

